### ISSUE TITLE
String Type Error when accessing admin

### ISSUE THREAD

**Issue by georgedm06** [magedin/magento2-module-trojan-request-blocker#1]
![Screenshot 2024-09-13 at 12 00 07 PM](https://github.com/user-attachments/assets/61724b75-4f60-42e5-afb7-09f8bd938e9b)

After installing the module and attempting to access the admin I received the following error.

TypeError: explode(): Argument #2 ($string) must be of type string, null given in /var/www/html/vendor/magedin/module-trojan-request-blocker/Model/Config.php:67
Stack trace:
#0 /var/www/html/vendor/magedin/module-trojan-request-blocker/Model/Config.php(67): explode()
#1 /var/www/html/vendor/magedin/module-trojan-request-blocker/Service/Patterns/ConfigPatterns.php(43): MagedIn\TrojanRequestBlocker\Model\Config->getAdditionalPatterns()
#2 /var/www/html/vendor/magedin/module-trojan-request-blocker/Service/PatternsLoader.php(63): MagedIn\TrojanRequestBlocker\Service\Patterns\ConfigPatterns->load()
#3 /var/www/html/vendor/magedin/module-trojan-request-blocker/Service/Validator/PostRequest.php(70): MagedIn\TrojanRequestBlocker\Service\PatternsLoader->load()
#4 /var/www/html/vendor/magedin/module-trojan-request-blocker/Service/Validator/PostRequest.php(52): MagedIn\TrojanRequestBlocker\Service\Validator\PostRequest->doValidatePostData()
#5 /var/www/html/vendor/magedin/module-trojan-request-blocker/Plugin/ValidateTrojanPostRequest.php(64): MagedIn\TrojanRequestBlocker\Service\Validator\PostRequest->validate()
#6 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(121): MagedIn\TrojanRequestBlocker\Plugin\ValidateTrojanPostRequest->beforeDispatch()
#7 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#8 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#9 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#10 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#11 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#12 {main}

**Comment by todorovj** [comment]
@tiagosampaio do you have any updates regarding this? 
Our client encountered the same issue

**Comment by tiagosampaio** [comment]
Hey, @georgedm06 and @todorovj. Thank you for opening this issue. The good news is that release [`1.0.1`](https://github.com/magedin/magento2-module-trojan-request-blocker/releases/tag/1.0.1) should fix this problem and is already available for you to download it and test it.

Please let me know if it works so I can close this issue.

Thanks,
-Tiago

**Comment by todorovj** [comment]
@tiagosampaio This is present, we installed the latest version, once the admin panel is opened there is still an error:
`1 exception(s):
Exception #0 (Exception): Warning: strpos(): Empty needle in /var/www/fashcon/b/fashcon-6550/vendor/magedin/module-trojan-request-blocker/Service/Validator/PostRequest.php on line 72

Exception #0 (Exception): Warning: strpos(): Empty needle in /var/www/fashcon/b/fashcon-6550/vendor/magedin/module-trojan-request-blocker/Service/Validator/PostRequest.php on line 72
<pre>#1 strpos() called at [vendor/magedin/module-trojan-request-blocker/Service/Validator/PostRequest.php:72]
#2 MagedIn\TrojanRequestBlocker\Service\Validator\PostRequest->doValidatePostData() called at [vendor/magedin/module-trojan-request-blocker/Service/Validator/PostRequest.php:52]
#3 MagedIn\TrojanRequestBlocker\Service\Validator\PostRequest->validate() called at [vendor/magedin/module-trojan-request-blocker/Plugin/ValidateTrojanPostRequest.php:64]
#4 MagedIn\TrojanRequestBlocker\Plugin\ValidateTrojanPostRequest->beforeDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:121]
#5 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php:32]
#6 Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#7 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#8 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#9 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#10 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#11 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#12 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>`
![TinyTake04-12-2024-03-37-00](https://github.com/user-attachments/assets/d1568d42-18b6-48a9-97cc-6a5efe8262a1)
![TinyTake04-12-2024-03-39-50](https://github.com/user-attachments/assets/11de4561-2556-4913-a5ea-41ae4b5ae885)

Also this is happening when product is added to the cart

**Comment by tiagosampaio** [comment]
@todorovj, thanks for your contribution. I'm going to review it and let you know about it.

**Comment by tiagosampaio** [comment]
@todorovj, try it now, please.

**Comment by todorovj** [comment]
@tiagosampaio you can resolve this, but I have one more thing, I reviewed your instructions on how to test this, and it will be of great help if you can share the test from Postman that you ran

**Comment by tiagosampaio** [comment]
@todorovj, in the `di.xml` file, you'll find some patterns that are tested by default.

https://github.com/magedin/magento2-module-trojan-request-blocker/blob/c1cb72d7c9dd7984c2de16ffe60e985d4ad66591/etc/di.xml#L22

```xml
            <argument name="patterns" xsi:type="array">
                <item name="10" xsi:type="string">this.getTemplateFilte</item>
                <item name="20" xsi:type="string">.addAfterFilterCallbac</item>
                <item name="30" xsi:type="string">.filter(</item>
                <item name="40" xsi:type="string">.Filter(</item>
                <item name="50" xsi:type="string">gettemplate</item>
                <item name="60" xsi:type="string">base64_</item>
                <item name="70" xsi:type="string">afterfiltercall</item>
                <item name="80" xsi:type="string">magdemo9816@proton.me</item>
            </argument>
```

In the API, if you try to post anything using one of these terms, the request is blocked. First instance, try creating a customer via API and setting the first name as `.addAfterFilterCallbac`.

I'm closing this ticket, as it looks like the issue is fixed. If you need further assistance with it, please reopen the issue.
